name: FX Signal Bot

on:
  schedule:
    - cron: "*/15 * * * *"   # 15分ごと（UTC）
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (empty repo OK)
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: npm ci || npm i
      - name: Run bot
        env:
          FOREX_API_KEY: ${{ secrets.FOREX_API_KEY }}
          WORKER_URL: ${{ secrets.WORKER_URL }}
          LINE_TO: ${{ secrets.LINE_TO }}
          PAIRS: ${{ secrets.PAIRS }}
          SILENT_UTC: ${{ secrets.SILENT_UTC }}
        run: npm start
